### ISSUE TITLE
woud it be possible to bundle chdman as well?

### ISSUE THREAD

**Issue by bmsuseluda** [flathub/org.mamedev.MAME#37] opened 2023-09-18 18:40 UTC
Hello and thank you for the work,

i would like to know if it would be possible to bundle chdman in this flatpak as well?
On devices like the steam deck i only can use flatpaks or appimages, but it would be great to compress roms on it.

thanks in advance

**Comment by taemdaemon** [comment] 2023-10-18 18:13
> chdman

Dupe of #31

**Closed** 2024-02-12 13:56 UTC
